# Site settings
title:          Rafael Vargas
description:    "Some tech stuff."
repository:     https://github.com/rafaelvargas/rafaelvargas.github.io/
url:            https:://rafaelvargas.dev/
baseurl:        ""
google_analytics: G-C2RXH4PPZ8

# Author
author:
  name:         Rafael Vargas
  url:          https://inf.ufrgs.br/~rflvargas
  email:        contact@rafaelvargas.dev
  github:       rafaelvargas
  linkedin:     rafaelflvargas

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate
  - jekyll-remote-theme

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5


