# Site settings
title:          Rafael Vargas
description:    "Notes on data engineering, analytics and software engineering."
repository:     https://github.com/rafaelvargas/rafaelvargas.github.io/
url:            https://rafaelvargas.dev
baseurl:        ""
google_analytics: G-C2RXH4PPZ8

# Author
author:
  name:         Rafael Vargas
  url:          https://rafaelvargas.dev/about/
  email:        contact@rafaelvargas.dev
  github:       rafaelvargas
  linkedin:     rafaelflvargas
  twitter:      rafaelflvargas

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Permalinks
permalink:      /:year/:month/:day/:title/

# Pagination
paginate: 5
paginate_path: "page/:num/"


feed:
  path: feed.xml
  limit: 15